// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAx8vmKI51JtN5jM2_GUj7ozlJJPZpszA',
    appId: '1:149886283467:web:9aef5164326600766bb54e',
    messagingSenderId: '149886283467',
    projectId: 'finnapp-b93d3',
    authDomain: 'finnapp-b93d3.firebaseapp.com',
    storageBucket: 'finnapp-b93d3.firebasestorage.app',
    measurementId: 'G-7RT1DELS2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5i5rFATstTdpbtUlhD1Ld9tfLSW5zoek',
    appId: '1:149886283467:android:32804dc7fb60868c6bb54e',
    messagingSenderId: '149886283467',
    projectId: 'finnapp-b93d3',
    storageBucket: 'finnapp-b93d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO2-JEGCIFrtjpFSxUlQvYxXhRYS_6kws',
    appId: '1:149886283467:ios:fba737b33dadaa4b6bb54e',
    messagingSenderId: '149886283467',
    projectId: 'finnapp-b93d3',
    storageBucket: 'finnapp-b93d3.firebasestorage.app',
    iosBundleId: 'com.example.finnapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO2-JEGCIFrtjpFSxUlQvYxXhRYS_6kws',
    appId: '1:149886283467:ios:fba737b33dadaa4b6bb54e',
    messagingSenderId: '149886283467',
    projectId: 'finnapp-b93d3',
    storageBucket: 'finnapp-b93d3.firebasestorage.app',
    iosBundleId: 'com.example.finnapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAx8vmKI51JtN5jM2_GUj7ozlJJPZpszA',
    appId: '1:149886283467:web:30d5b2233e15755a6bb54e',
    messagingSenderId: '149886283467',
    projectId: 'finnapp-b93d3',
    authDomain: 'finnapp-b93d3.firebaseapp.com',
    storageBucket: 'finnapp-b93d3.firebasestorage.app',
    measurementId: 'G-RS32MXHEMP',
  );
}
